import { RefreshCw, Save, UserPlus } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { adminApi } from "../api/admin";
import { EmptyState } from "../components/EmptyState";
import { ErrorAlert } from "../components/ErrorAlert";
import { LoadingState } from "../components/LoadingState";
import { Modal } from "../components/Modal";
import { PageHeader } from "../components/PageHeader";
import { formatDate, getErrorMessage } from "../lib/format";

const plannerSchema = z.object({
  email: z.string().email("Enter a valid planner email"),
  password: z.string().min(6, "Temporary password must be at least 6 characters"),
});

function generatePassword() {
  const random = Math.random().toString(36).slice(2, 8);
  return `Planner-${random}42`;
}

export function UsersPage() {
  const [planners, setPlanners] = useState([]);
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [activeFilter, setActiveFilter] = useState("");
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [editingPlanner, setEditingPlanner] = useState(null);
  const [editPassword, setEditPassword] = useState("");
  const {
    register,
    handleSubmit,
    setValue,
    setError: setFormError,
    reset,
    formState: { errors },
  } = useForm({
    defaultValues: { email: "", password: generatePassword() },
  });

  const activeParam = useMemo(() => {
    if (activeFilter === "") return undefined;
    return activeFilter === "true";
  }, [activeFilter]);

  async function loadPlanners() {
    setLoading(true);
    setError("");
    try {
      const result = await adminApi.listPlanners({
        page,
        limit: 10,
        active: activeParam,
      });
      setPlanners(result.planners || []);
      setTotalPages(result.pages || 1);
    } catch (err) {
      setError(getErrorMessage(err, "Failed to load planners"));
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    loadPlanners();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [page, activeParam]);

  const submitCreate = async (values) => {
    setError("");
    setNotice("");
    const parsed = plannerSchema.safeParse(values);
    if (!parsed.success) {
      parsed.error.issues.forEach((issue) => setFormError(issue.path[0], { message: issue.message }));
      return;
    }

    try {
      setSubmitting(true);
      await adminApi.createPlanner(parsed.data);
      setNotice(`Planner ${parsed.data.email} created.`);
      reset({ email: "", password: generatePassword() });
      await loadPlanners();
    } catch (err) {
      setError(getErrorMessage(err, "Failed to create planner"));
    } finally {
      setSubmitting(false);
    }
  };

  const toggleStatus = async (planner) => {
    setError("");
    setNotice("");
    try {
      await adminApi.setPlannerStatus(planner._id, !planner.active);
      setNotice(`${planner.email} ${planner.active ? "deactivated" : "activated"}.`);
      await loadPlanners();
    } catch (err) {
      setError(getErrorMessage(err, "Failed to update planner status"));
    }
  };

  const savePlannerEdit = async () => {
    if (!editingPlanner) return;
    setError("");
    setNotice("");
    const payload = { active: editingPlanner.active };
    if (editPassword) {
      if (editPassword.length < 6) {
        setError("Password must be at least 6 characters.");
        return;
      }
      payload.password = editPassword;
    }

    try {
      setSubmitting(true);
      await adminApi.updatePlanner(editingPlanner._id, payload);
      setNotice(`${editingPlanner.email} updated.`);
      setEditingPlanner(null);
      setEditPassword("");
      await loadPlanners();
    } catch (err) {
      setError(getErrorMessage(err, "Failed to update planner"));
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div>
      <PageHeader
        title="Planner accounts"
        description="Create planner users and manage active or inactive status."
      />

      <div className="space-y-3">
        <ErrorAlert message={error} />
        {notice ? <div className="rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{notice}</div> : null}
      </div>

      <section className="mt-5 rounded-lg border border-slate-200 bg-white p-5 shadow-sm">
        <div className="mb-4 flex items-center justify-between gap-3">
          <div>
            <h3 className="text-lg font-bold text-slate-950">Create New Planner</h3>
            <p className="text-sm text-slate-500">A temporary password is generated by default and can be replaced.</p>
          </div>
          <button
            type="button"
            className="inline-flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-sm font-bold text-slate-700 hover:bg-slate-50"
            onClick={() => setValue("password", generatePassword())}
          >
            <RefreshCw className="h-4 w-4" />
            Generate password
          </button>
        </div>

        <form className="grid gap-3 md:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto]" onSubmit={handleSubmit(submitCreate)}>
          <label>
            <span className="text-sm font-semibold text-slate-700">Email</span>
            <input
              type="email"
              className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2.5 outline-none focus:border-teal-600 focus:ring-4 focus:ring-teal-100"
              {...register("email")}
            />
            {errors.email ? <span className="mt-1 block text-xs font-semibold text-rose-600">{errors.email.message}</span> : null}
          </label>
          <label>
            <span className="text-sm font-semibold text-slate-700">Temporary password</span>
            <input
              type="text"
              className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2.5 outline-none focus:border-teal-600 focus:ring-4 focus:ring-teal-100"
              {...register("password")}
            />
            {errors.password ? <span className="mt-1 block text-xs font-semibold text-rose-600">{errors.password.message}</span> : null}
          </label>
          <button
            type="submit"
            disabled={submitting}
            className="mt-6 inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-teal-700 px-4 py-2 text-sm font-bold text-white hover:bg-teal-800 disabled:opacity-50"
          >
            <UserPlus className="h-4 w-4" />
            Create
          </button>
        </form>
      </section>

      <section className="mt-5 rounded-lg border border-slate-200 bg-white shadow-sm">
        <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 p-4">
          <h3 className="text-lg font-bold text-slate-950">Planner List</h3>
          <select
            className="rounded-lg border border-slate-300 px-3 py-2 text-sm outline-none focus:border-teal-600"
            value={activeFilter}
            onChange={(event) => {
              setPage(1);
              setActiveFilter(event.target.value);
            }}
          >
            <option value="">All statuses</option>
            <option value="true">Active</option>
            <option value="false">Inactive</option>
          </select>
        </div>

        {loading ? (
          <LoadingState label="Loading planners" />
        ) : planners.length ? (
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-slate-200 text-left text-sm">
              <thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500">
                <tr>
                  <th className="px-4 py-3 font-bold">Email</th>
                  <th className="px-4 py-3 font-bold">Status</th>
                  <th className="px-4 py-3 font-bold">Created At</th>
                  <th className="px-4 py-3 font-bold">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {planners.map((planner) => (
                  <tr key={planner._id}>
                    <td className="px-4 py-4 font-semibold text-slate-950">{planner.email}</td>
                    <td className="px-4 py-4">
                      <span
                        className={[
                          "rounded-full px-2.5 py-1 text-xs font-bold",
                          planner.active ? "bg-emerald-100 text-emerald-700" : "bg-slate-100 text-slate-700",
                        ].join(" ")}
                      >
                        {planner.active ? "active" : "inactive"}
                      </span>
                    </td>
                    <td className="px-4 py-4 text-slate-600">{formatDate(planner.createdAt)}</td>
                    <td className="px-4 py-4">
                      <div className="flex flex-wrap gap-2">
                        <button
                          type="button"
                          className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-bold text-slate-700 hover:bg-slate-50"
                          onClick={() => {
                            setEditingPlanner(planner);
                            setEditPassword("");
                          }}
                        >
                          Edit
                        </button>
                        <button
                          type="button"
                          className={[
                            "rounded-lg px-3 py-1.5 text-xs font-bold",
                            planner.active
                              ? "border border-rose-200 text-rose-700 hover:bg-rose-50"
                              : "border border-emerald-200 text-emerald-700 hover:bg-emerald-50",
                          ].join(" ")}
                          onClick={() => toggleStatus(planner)}
                        >
                          {planner.active ? "Deactivate" : "Activate"}
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            <div className="flex items-center justify-between border-t border-slate-200 px-4 py-3 text-sm text-slate-600">
              <span>Page {page} of {totalPages}</span>
              <div className="flex gap-2">
                <button
                  type="button"
                  disabled={page <= 1}
                  onClick={() => setPage((current) => Math.max(1, current - 1))}
                  className="rounded-lg border border-slate-200 px-3 py-1.5 font-bold hover:bg-slate-50 disabled:opacity-50"
                >
                  Previous
                </button>
                <button
                  type="button"
                  disabled={page >= totalPages}
                  onClick={() => setPage((current) => current + 1)}
                  className="rounded-lg border border-slate-200 px-3 py-1.5 font-bold hover:bg-slate-50 disabled:opacity-50"
                >
                  Next
                </button>
              </div>
            </div>
          </div>
        ) : (
          <div className="p-5">
            <EmptyState title="No planners found" description="Create a planner account or adjust the status filter." />
          </div>
        )}
      </section>

      {editingPlanner ? (
        <Modal title={`Edit ${editingPlanner.email}`} onClose={() => setEditingPlanner(null)}>
          <div className="space-y-4">
            <label className="flex items-center gap-2 rounded-lg border border-slate-200 p-3 text-sm font-semibold text-slate-700">
              <input
                type="checkbox"
                className="h-4 w-4 accent-teal-700"
                checked={editingPlanner.active}
                onChange={(event) => setEditingPlanner((current) => ({ ...current, active: event.target.checked }))}
              />
              Account active
            </label>

            <label className="block">
              <span className="text-sm font-semibold text-slate-700">New password</span>
              <input
                type="text"
                value={editPassword}
                onChange={(event) => setEditPassword(event.target.value)}
                placeholder="Leave blank to keep current password"
                className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2.5 outline-none focus:border-teal-600 focus:ring-4 focus:ring-teal-100"
              />
            </label>

            <div className="flex flex-wrap gap-2">
              <button
                type="button"
                disabled={submitting}
                onClick={savePlannerEdit}
                className="inline-flex items-center gap-2 rounded-lg bg-teal-700 px-4 py-2 text-sm font-bold text-white hover:bg-teal-800 disabled:opacity-50"
              >
                <Save className="h-4 w-4" />
                Save
              </button>
              <button
                type="button"
                className="rounded-lg border border-slate-200 px-4 py-2 text-sm font-bold text-slate-700 hover:bg-slate-50"
                onClick={() => setEditPassword(generatePassword())}
              >
                Generate password
              </button>
            </div>
          </div>
        </Modal>
      ) : null}
    </div>
  );
}
